INSERT INTO escola (nome)
VALUES  ('E.M. Professora Maria Ângela Moreira Pinto'),
        ('Escola Municipal Paulo Freire'),
        ('CIEP 449 Governador Leonel de Moura Brizola Brasil-França'),
        ('E.M. Professor Horácio Pacheco'),
        ('Colégio Estadual Baltazar Bernardino'),
        ('E.M. Dr. Alberto Fr. Torres'),
        ('Colégio Graham Bell'),
        ('SESI - Centro de Atividades São Gonçalo'),
        ('E.M. Maestro Heitor Villa Lobos'),
        ('E.M Pastor Ricardo Parise'),
        ('CIEP Brizolão 450 - Emiliano Di Cavalcanti'),
        ('E.M. Vera Lúcia Machado'),
        ('E.M. Francisco Portugal Neves'),
        ('C.E Professora Antonieta Palmeira'),
        ('Colégio Estadual Paulo Assis Ribeiro'),
        ('E.M. Felisberto de Carvalho'),
        ('C.E Paulo Assis Ribeiro'),
        ('Colégio Estadual Manuel de Abreu'),
        ('Colégio Charitas'),
        ('Colégio Estadual Caio Francisco de Figueiredo'),
        ('Colégio Estadual Hilário Ribeiro'),
        ('Colégio Estadual Aurelino Leal'),
        ('Colégio Estadual Aníbal Viriato de Azevedo'),
        ('Colégio Odete São Paio'),
        ('Colégio Plínio Leite'),
        ('Colégio Estadual Leopoldo Fróes'),
        ('CIEP 513 George Savalla Gomes'),
        ('CIEP Brizolão 450 - Emiliano Di Cavalcanti'),
        ('C.E Dalila de Oliveira Costa'),
        ('Escola Municipal Maralegre'),
        ('E. M. Mestra Fininha'),
        ('CIEP Brizolão 448 - Ruy Frazão Soares'),
        ('CIEP 050 Pablo Neruda'),
        ('E.M. Jornalista Alberto Torres'),
        ('Colégio Estadual Capistrano de Abreu'),
        ('Escola Municipal Professora Lúcia Maria Silveira Rocha'),
        ('E.M. Honorina de Carvalho'),
        ('Colégio Estadual Baltazar Bernardino'),
        ('Colégio Estadual Mullulo da Veiga'),
        ('E.E. São Domingos Sávio'),
        ('Colégio estadual Dr. João Gomes de Mattos Sobrinho'),
        ('E.M. Altivo César'),
        ('E.M. Professor Paulo de Almeida Campos'),
        ('E.M Francisco Portugal Neves'),
        ('Colégio Nossa Sra. da Assunção'),
        ('Colégio Estadual Duque de Caxias'),
        ('Colégio Estadual Raul Vidal'),
        ('Colégio Estadual Almirante Tamadaré'),
        ('CEFET'),
        ('E.E Ismael Coutinho'),
        ('Escola Municipal Professor Dario de Souza Castelo'),
        ('Escola Municipal Antonio Coutinho de Azevedo'),
        ('Colégio Estadual Professora Alcina Rodrigues Lima'),
        ('Colégio Estadual David Capistrano'),
        ('E.M. Levi Carneiro'),
        ('Colégio Estadual Doutor Moacyr Meirelles Padilha'),
        ('E.M. Julia Cortines'),
        ('Colégio Estadual Professora Adelia Martins'),
        ('E.M. Professora Lúcia Maria Silveira Rocha'),
        ('CIEP 448 Ruy Frazão Soares'),
        ('Sistema Educacional Pai Inteligente'),
        ('C.E Guilherme Briggs'),
        ('Colégio Estadual Leopoldina da Silveira'),
        ('E.M. Professor Dario de Souza Castello'),
        ('E.M. Rachide da Gloria Salim Saker'),
        ('Colégio Estadual Maria Pereira das Neves'),
        ('Colégio Estadual Ministro José de Moura e Filho'),
        ('Instituto de Educação Professor Ismael Coutinho (IEPIC)'),
        ('Colégio Estadual Melchiades Picanço'),
        ('CIEP 121 Professor Joadélio Codeço'),
        ('Colégio Estadual Barão de Macaubas'),
        ('Centro Educacional Marins Miranda'),
        ('Colégio Nossa Senhora da Assunção'),
        ('Colégio Estadual Fernando Magalhães'),
        ('Liceu Nilo Peçanha'),
        ('Colégio Estadual Amanda Velasco'),
        ('Colégio Estadual Joaquim Távora'),
        ('escola Municipal Rachide da Gloria Salim Saker'),
        ('CIEP Brizolão 309 - Zuzu Angel'),
        ('Colégio Estadual Machado de Assis'),
        ('Colégio Estadual Cizinio Soares Pinto'),
        ('E. M. Helena Antipoff'),
        ('Colégio Estadual Coronel Serrado'),
        ('Colégio Paraquett'),
        ('Centro Educacional Lazares'),
        ('Escola Municipal Professor Paulo de Almeida Campos'),
        ('UFF'),
        ('E.M. Padre Leonel França'),
        ('Colégio Estadual Dr. Rodolpho Siqueira'),
        ('Escola Municipal Raul Veiga'),
        ('Escolinha da Tia Suzana'),
        ('Colégio Estadual Dr. Luciano Pestre'),
        ('Escola Rachel Germano Azevedo de Lira'),
        ('C.E. Walter Orlandini'),
        ('Colégio Estadual Professor Francisco de Paula Achilles'),
        ('Grupo de Ensino Miranda Barroso'),
        ('FAETEC - Henrique Lage'),
        ('Escola Municipal Julia Cortines'),
        ('Colégio Municipal Honorina de Carvalho'),
        ('Colégio Estadual Monteiro de Carvalho'),
        ('COL. MUNICIPAL PRESIDENTE CASTELLO BRANCO'),
        ('Colégio Curso Progressão Niterói'),
        ('Colégio Estadual Conselheiro Josino'),
        ('CIEP BRIZOLÃO 239 Professora Elza Vianna Fialho'),
        ('Colégio Estadual Cizínio Soares Pinto'),
        ('Instituto de Educação Clélia Nanci'),
        ('Colégio Estadual Prof.ª Odysséa S. de Siqueira'),
        ('Colégio Estadual Dôrval Ferreira da Cunha'),
        ('Escola Estadual Maria Pereira das Neves'),
        ('Grupo Attrium de Ensino'),
        ('Escola Estadual Cruzeiro do Sul'),
        ('E.M. Maralegre'),
        ('E.M. Beatriz Eliane Cordeiro Santos'),
        ('Escola Municipal José de Anchieta'),
        ('C E Maria Pereira das Neves'),
        ('Colégio Estadual Zuleika Raposo Valladares'),
        ('ISERJ'),
        ('Centro Educativo Infantil São José'),
        ('E.M. Profª Maria de Lourdes Barbosa'),
        ('C.E. Embaixador Raul Fernandes'),
        ('Colégio Salesiano Santa Rosa'),
        ('Colégio Estadual Infante Dom Henrique'),
        ('Colégio Estadual Mário Tamborindeguy'),
        ('Colégio Estadual Walter Orlandini'),
        ('Jardim Escola Lápis de Cor'),
        ('CIEP 249 - Pastor Waldemar Zarro'),
        ('Colégio Estadual Santos Dias'),
        ('Escola Municipal Maestro Heitor Villa Lobos'),
        ('Instituto de Educação Professor Manuel Marinho'),
        ('E. E. Leonor Franco Moreira'),
        ('Colégio Pensi Lobo Torres'),
        ('Centro Educacional Região Oceânica'),
        ('Escola Municipal Beatriz Eliane Cordeiro Santos'),
        ('Colégio Estadual Cinamomo'),
        ('Escola Estadual Cônego Goulart'),
        ('CIEP Brizolão 238 - Dr. Ilton Faria da Costa'),
        ('CIEP Brizolão 412 - Dr. Zerbrini'),
        ('Escola Municipal Dom José Pereira Alves'),
        ('Escola Municipal Júlia Cortines'),
        ('Escola Municipal Professora Maria Ângela Moreira Pinto'),
        ('C.E. DR. MOACYR MEIRELLES PADILHA '),
        ('Escola Municipal Honorina de Carvalho'),
        ('E.M. João Brazil'),
        ('C.E. José de Moura e Silva'),
        ('Colégio Pedro II'),
        ('Colégio Estadual Professora Luiza Honoraria do Prado'),
        ('Ciep Brizolão 246 Professora Adalgisa Cabral de Faria'),
        ('Colégio e Curso Darwin LTDA'),
        ('E.M. Professor Marcos Waldemar de Freitas Reis'),
        ('Colégio Estadual Professora Adélia Martins'),
        ('CEJA'),
        ('C.E. Pandiá Calógera'),
        ('Escola Municipal Sitio do Ipê'),
        ('Escola Municipal Francisco Portugal Neves'),
        ('Escola Municipal Helena Antipoff'),
        ('Instituto de Educação Aplicada Teresa de Lisieux'),
        ('Colégio Estadual Pinto Lima'),
        ('E.M. Prof. André Trouche'),
        ('E. M. Sitio do Ipê'),
        ('CIEP 307 - Djanira'),
        ('Associação da Irmandade de São Vicente de Paulo'),
        ('Colégio Pluz'),
        ('Colégio e Curso Pensi'),
        ('Colégio Vital Brasil'),
        ('Colégio Estadual Cristovão Colombo'),
        ('Escola Municipal Lucia Maria Silveira Rocha'),
        ('Colégio Platô'),
        ('Colégio Estadual Ismael Branco'),
        ('Escola Municipal Eulalia da Silveira Bragança'),
        ('Escola Estadual Conego Goulart'),
        ('Teste - Projeto Grael'),
        ('Escola municipal Célia Pereira da Rosa'),
        ('CIEP 423 Mora Guimarães'),
        ('Colégio Estadual Pandia  Calogeras'),
        ('Colégio Estadual Capitão Oswaldo Ornellas'),
        ('Escola Técnica Estadual Henrique Lage'),
        ('ISJB Colégio Salesiano Santa Rosa'),
        ('Salesiano Santa Rosa'),
        ('Colégio Estadual Manoel de Abreu'),
        ('ENCCEJA - Secretaria do Estado de Educação'),
        ('Colégio Estadual Augusto Cezário Diaz André'),
        ('Colégio Escrevendo o Futuro Educação LTDA - Grafitinho'),
        ('Colégio Universitário Geraldo Reis'),
        ('Colégio Estadual Dr. Souza Soares'),
        ('CIEP 412 Doutor Zerbini'),
        ('Colégio Estadual Coronel  João Tarcísio Bueno'),
        ('Escola Municipal levi Carneiro'),
        ('Centro Educacional Salgado Monteiro'),
        ('Sistema Elite de Ensino'),
        ('Escola Municipal Cristina de Lima Corrêa'),
        ('Escola Municipal Maria Cristina de Lima Corrêa'),
        ('Escola Municipal Santos Dumont'),
        ('EE Antônio Delphino dos Santos - MG'),
        ('Fundação Municipal de Educação de Niterói'),
        ('CIEP 409 Professora Alaíde de Figueiredo Santos'),
        ('UMEI Darcy Ribeiro'),
        ('Colégio Estadual Conselheiro Macedo Soares'),
        ('Escola Municipal Paulo Reglus Neves '),
        ('Escola Agostinho Cunha'),
        ('Creche Escola Quintal Girassol'),
        ('Colégio Estadual Euclydes Paulo da Silva'),
        ('Colégio Estadual Paulinho Pinheiro Baptista');