INSERT INTO sub_bairro (nome, id_bairro)
VALUES  ('Preventório', 1),
        ('Anaia Pequeno', 1),
        ('Charitas', 1),
        ('Zumbi', 1),
        ('Caixa d''água', 2),
        ('Mutuapira', 2),
        ('Salina', 2),
        ('Varzea', 2),
        ('Pendotiba', 3),
        ('Anáia Pequeno', 3),
        ('Niterói', 3),
        ('Atalaia', 3),
        ('Vila Candoza', 4),
        ('Preventória', 4),
        ('Cachoeiras', 4),
        ('Chácara', 4),
        ('Cascarejo', 5),
        ('Ponta da Ilha', 5),
        ('Maravista', 5),
        ('Lazaredo', 5),
        ('Muriqui', 5),
        ('Morro do Cavalão', 5),
        ('Riodade', 5),
        ('Paciência', 5),
        ('Serra Grande', 6),
        ('Várzea', 6),
        ('Tribobo', 6),
        ('Preventorio', 6),
        ('Peixe-Galo', 7),
        ('Santa Teresa', 7),
        ('Jardim Miriambi', 7),
        ('Badú', 7),
        ('Jurujuba', 8),
        ('salina', 8),
        ('Cafubá', 8),
        ('LTO Campo Novo', 8),
        ('Palácio', 9),
        ('Portuguesa', 9),
        ('Vila Progresso', 9),
        ('Maloca', 9),
        ('Final', 10),
        ('Morro do Ceu', 10),
        ('Itaipú', 10),
        ('Cavalão', 10),
        ('Peixe Galo', 11),
        ('Morro do Estado', 11),
        ('Amendoeira', 11),
        ('Salinas', 11);